name: ProvisionVM
on:
  workflow_dispatch:
   inputs:
      VmName:
        description: 'Name of VM'
        required: true
      Vmid:
        description: 'VMID of VM'
        required: true
      VmCount:
        description: 'Number of VMs to create'
        required: true
        default: "1"
      From_Vm:
        description: 'VM template to clone'
        required: true
        default: 'Ubuntu-24.04'
      Memory:
        description: 'RAM size to allocate to VM'
        required: true
        default: '2048'
      Cores:
        description: 'Cores to allocate to VM'
        required: true
        default: '4'
      DiskSize:
        description: 'Size of VM disk'
        required: true
        default: '10G'
      Balloon:
        description: 'Default balloon size'
        required: true
        default: '512'

jobs:
  CloneRepository:
    runs-on: infra-node
    container:
      image: alpine/git:v2.47.1
    steps:
      - name: Git Clone
        run: git clone https://github.com/zazathomas/compliance-as-code.git .
  RunTerraform:
    needs: CloneRepository
    runs-on: infra-node
    container:
      image: vydev/terraform:1.10.2
      env:
        TF_VAR_vm_name: ${{ github.event.inputs.VmName }} 
        TF_VAR_vmid: ${{ github.event.inputs.Vmid }}
        TF_VAR_vm_count: ${{ github.event.inputs.VmCount }}
        TF_VAR_memory: ${{ github.event.inputs.Memory }}
        TF_VAR_cores: ${{ github.event.inputs.Cores }}  
        TF_VAR_disk_size: ${{ github.event.inputs.DiskSize }}
        TF_VAR_clone_from_vm: ${{ github.event.inputs.From_Vm }}
        TF_VAR_balloon: ${{ github.event.inputs.Balloon }}
        TF_VAR_ciuser: ${{ secrets.CIUSER }}
        TF_VAR_cipassword: ${{ secrets.CIPASSWORD }}
        TF_VAR_proxmox_api_secret: ${{ secrets.PROXMOX_API_SECRET }}
        TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_API_TOKEN }}
    steps:
      - name: Run Terraform Operations
        run: |
          cd terraform/proxmox/vm && mkdir -p ~/.ssh && echo '${{ secrets.SSH_PUBLIC_KEY }}' > ~/.ssh/id_rsa.pub
          terraform init
          terraform plan
          terraform apply --auto-approve

  CleanWS:
    needs: RunTerraform
    runs-on: infra-node
    if: always()
    container:
      image: alpine/git:v2.47.1
    steps:
      - name: Cleanup build folder
        run: ls -la ./ && rm -rf ./* || true && rm -rf ./.??* || true && ls -la ./
    
