name: Test
on:
  workflow_dispatch:
jobs:
  test-job:
    runs-on: infra-node
    container:
      image: alpine/git:v2.47.1
    steps:
      - name: Git Clone
        run: git clone https://github.com/zazathomas/Jenkins-for-DevSecOps.git

  sample:
    needs: test-job
    runs-on: infra-node
    container:
      image: alpine
    steps:
      - name: check
        run: |
          ls -l
